<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<packaging>jar</packaging>

	<parent>
		<groupId>org.sonatype.oss</groupId>
		<artifactId>oss-parent</artifactId>
		<version>9</version>
		<relativePath/>
	</parent>

	<groupId>io.autonomx</groupId>
	<artifactId>autonomx-core</artifactId>
	<version>1.3.2</version>

	<name>Autonomx Core</name>
	<description>Open-source automation testing framework for UI and API testing across web, mobile, and Windows platforms.</description>
	<url>https://github.com/autonomx/AutonomxCore</url>

	<licenses>
		<license>
			<name>MIT License</name>
			<url>https://opensource.org/license/mit/</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>ehsanmatean</id>
			<name>Ehsan Matean</name>
			<organization>Autonomx</organization>
			<organizationUrl>https://github.com/autonomx</organizationUrl>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:https://github.com/autonomx/AutonomxCore.git</connection>
		<developerConnection>scm:git:ssh://git@github.com/autonomx/AutonomxCore.git</developerConnection>
		<url>https://github.com/autonomx/AutonomxCore</url>
	</scm>

	<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<release>17</release>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.0.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<!--skip source code. remove attached-source <configuration> <skipSource>true</skipSource> 
							</configuration> -->
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.1.0</version>
				 <configuration>
					 <source>8</source>
			         <additionalparam>-Xdoclint:none</additionalparam>
			         <additionalOptions>-Xdoclint:none</additionalOptions>
			         <additionalJOption>-Xdoclint:none</additionalJOption>
			         <arguments>-Dmaven.javadoc.skip=true</arguments>
			      </configuration>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>sign-artifacts</id>
						<phase>verify</phase>
						<goals>
							<goal>sign</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
				<plugin>
				  <groupId>org.sonatype.central</groupId>
				  <artifactId>central-publishing-maven-plugin</artifactId>
				  <version>0.11.0</version>
				  <extensions>true</extensions>
				  <configuration>
				    <publishingServerId>central</publishingServerId>
				    <autoPublish>false</autoPublish>
				  </configuration>
			</plugin>
			
		</plugins>
	</build>

	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
	</distributionManagement>
	

	<repositories>

		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>

	</repositories>

	<dependencyManagement>
		<dependencies>
			<!-- Keep Netty modules on one patched 4.1.x release. -->
			<dependency>
				<groupId>io.netty</groupId>
				<artifactId>netty-bom</artifactId>
				<version>4.1.136.Final</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<!-- Azure Service Bus 3.6.7 brings this transitively. -->
			<dependency>
				<groupId>org.asynchttpclient</groupId>
				<artifactId>async-http-client</artifactId>
				<version>2.15.0</version>
			</dependency>

			<!-- SikuliX 2.0.5 brings the vulnerable Jython 2.7.2 dependency. -->
			<dependency>
				<groupId>org.python</groupId>
				<artifactId>jython-slim</artifactId>
				<version>2.7.4</version>
			</dependency>

			<!-- Tess4J/PDFBox currently resolve Bouncy Castle 1.83. -->
			<dependency>
				<groupId>org.bouncycastle</groupId>
				<artifactId>bc-jdk18on-bom</artifactId>
				<version>1.84</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>


<dependencies>
	
		<dependency>
		    <groupId>org.apache.commons</groupId>
		    <artifactId>commons-lang3</artifactId>
		    <version>3.20.0</version>
		</dependency>
	
		<dependency>
   			 <groupId>com.google.guava</groupId>
		    <artifactId>guava</artifactId>
		    <version>33.6.0-jre</version>
		</dependency>


		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>6.3.4</version>
		</dependency>

		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>4.45.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.26.1</version>
		</dependency>	

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jul-to-slf4j</artifactId>
			<version>2.0.18</version>
		</dependency>	

		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>5.1.2</version>
			<exclusions>
				<exclusion>
					<groupId>org.projectlombok</groupId>
					<artifactId>lombok</artifactId>
				</exclusion>
			</exclusions>
		</dependency>


	<!-- https://mvnrepository.com/artifact/javax.mail/mail -->
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.5.0-b01</version>
		</dependency>

		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>10.1.1</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.5.1</version>
		</dependency>
		<dependency>
			<groupId>com.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>5.12.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-csv</artifactId>
			<version>1.14.1</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/io.rest-assured/rest-assured -->
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>5.5.7</version>
			<exclusions>
				<exclusion>
					<groupId>org.codehaus.groovy</groupId>
					<artifactId>groovy</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.skyscreamer</groupId>
			<artifactId>jsonassert</artifactId>
			<version>1.5.3</version>
			<exclusions>
				<exclusion>
					<groupId>com.vaadin.external.google</groupId>
					<artifactId>android-json</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>2.9.0</version>
		</dependency>

		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-storage</artifactId>
			<version>8.6.6</version>
		</dependency> 
		
		<dependency>
		    <groupId>com.fasterxml.jackson.core</groupId>
		    <artifactId>jackson-core</artifactId>
		    <version>2.20.1</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox -->
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>3.0.7</version>
		</dependency>

		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.14.0</version>
			<scope>compile</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all -->

		<dependency>
			<groupId>com.beust</groupId>
			<artifactId>jcommander</artifactId>
			<version>1.82</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.codehaus.groovy/groovy -->
		<dependency>
			<groupId>org.codehaus.groovy</groupId>
			<artifactId>groovy</artifactId>
			<version>3.0.25</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20260522</version>
		</dependency>

		<dependency>
			<groupId>com.xamarin.testcloud</groupId>
			<artifactId>appium</artifactId>
			<version>1.1</version>
		</dependency>

		<dependency>
			<groupId>com.microsoft.appcenter</groupId>
			<artifactId>appium-test-extension</artifactId>
			<version>1.6</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient -->
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.14</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.testng/testng -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.12.0</version>
		</dependency>



		<!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>42.7.13</version>
		</dependency>

		<dependency>
			<groupId>org.zeroturnaround</groupId>
			<artifactId>zt-zip</artifactId>
			<version>1.18.1</version>
			<type>jar</type>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.sikulix/sikulixapi -->
		<dependency>
			<groupId>com.sikulix</groupId>
			<artifactId>sikulixapi</artifactId>
			<version>2.0.5</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-nop</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- https://mvnrepository.com/artifact/net.sourceforge.tess4j/tess4j -->
		<dependency>
			<groupId>net.sourceforge.tess4j</groupId>
			<artifactId>tess4j</artifactId>
			<version>5.19.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>log4j-over-slf4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-classic</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-servicebus</artifactId>
			<version>3.6.7</version>
			<exclusions>
				<exclusion>
					<groupId>io.reactivex</groupId>
					<artifactId>rxjava</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.xmlunit</groupId>
			<artifactId>xmlunit-matchers</artifactId>
			<version>2.13.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.reflections/reflections -->
		<dependency>
			<groupId>org.reflections</groupId>
			<artifactId>reflections</artifactId>
			<version>0.10.2</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.google.auto.service/auto-service -->
		<dependency>
			<groupId>com.google.auto.service</groupId>
			<artifactId>auto-service</artifactId>
			<version>1.1.1</version>
		</dependency>

		<!-- screen recorder -->
		<dependency>
			<groupId>com.pojosontheweb</groupId>
			<artifactId>monte-repack</artifactId>
			<version>1.1</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.maven.shared/maven-invoker -->
		<dependency>
			<groupId>org.apache.maven.shared</groupId>
			<artifactId>maven-invoker</artifactId>
			<version>3.3.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/net.lingala.zip4j/zip4j -->
		<dependency>
			<groupId>net.lingala.zip4j</groupId>
			<artifactId>zip4j</artifactId>
			<version>2.11.6</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.rabbitmq/amqp-client -->
		<dependency>
			<groupId>com.rabbitmq</groupId>
			<artifactId>amqp-client</artifactId>
			<version>5.34.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients -->
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>4.3.1</version>
		</dependency>

		<dependency>
			<groupId>com.thoughtworks.paranamer</groupId>
			<artifactId>paranamer</artifactId>
			<version>2.8.3</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.14.1</version>
		</dependency>

		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-artifact</artifactId>
			<version>3.9.16</version>
		</dependency>

		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-model</artifactId>
			<version>3.9.16</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.apache.ant/ant -->
		<dependency>
			<groupId>org.apache.ant</groupId>
			<artifactId>ant</artifactId>
			<version>1.10.17</version>
		</dependency>

		<!-- JavaScript engine used in data logic validation. Keep the engine and script engine versions aligned. -->
		<dependency>
			<groupId>org.graalvm.js</groupId>
			<artifactId>js-community</artifactId>
			<version>24.1.0</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.graalvm.js</groupId>
			<artifactId>js-scriptengine</artifactId>
			<version>24.1.0</version>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/com.google.googlejavaformat/google-java-format -->
		<dependency>
		    <groupId>com.google.googlejavaformat</groupId>
		    <artifactId>google-java-format</artifactId>
		    <version>1.24.0</version>
		</dependency>
		
		
		  <!-- https://mvnrepository.com/artifact/io.netty/netty-handler -->
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-handler</artifactId>
			<version>4.1.136.Final</version>
		</dependency>
        
        <!-- 5.1.1 is giving duplicate error on azure -->
        <dependency>
		  <groupId>com.epam.reportportal</groupId>
		  <artifactId>agent-java-testng</artifactId>
		  <version>5.6.8</version>
        </dependency>
		
		<dependency>
		  <groupId>com.epam.reportportal</groupId>
		  <artifactId>logger-java-log4j</artifactId>
		  <version>5.4.0</version>
		</dependency>
		<dependency>
		    <groupId>com.squareup.retrofit2</groupId>
		    <artifactId>adapter-rxjava2</artifactId>
		    <version>3.0.0</version>
		    <exclusions>
		    	<exclusion>
		    		<groupId>io.reactivex.rxjava2</groupId>
		    		<artifactId>rxjava</artifactId>
		    	</exclusion>
		    </exclusions>
		</dependency>
		
		
		
	</dependencies>
	
	<profiles>
	</profiles>
</project>
